### PR TITLE
Update to upstream v0.24.0

### PR DESCRIPTION
**Pull request by aptomaKetil**

### CODE REVIEW

**Comment by aptomaKetil** [comment]
There's something off with the resize flags, they're no longer producing the same output. Will have to debug further.

**Comment by aptomaKetil** [comment]
Error was in the shim. This is good to go @martinj. There are two test runs that fail with segfault on muslC, which I'm inclined to ignore. All the platforms we use pass.

**Comment by martinj** [comment]
We don't have a test for the change we initially made in this fork "retain colour profile", have you validated this still works?

**Comment by aptomaKetil** [comment]
No, and I don't really remember what the change accomplishes. What should we be testing for?

**Comment by martinj** [comment]
I hardly remember my self. If we convert a CMYK image the output should use the same color profile "CMYK"

**Comment by aptomaKetil** [comment]
Right. I'll see if I can add a test somewhere.

**Comment by aptomaKetil** [comment]
Added test for profile retention.

**Pull request closed without merging**
